### PR TITLE
adding documentation for 'Validation' type

### PR DESCRIPTION
**Pull request by enelson**
Let me know if this is something you'd like to have on the Javaslang site. Thanks Daniel.

### CODE REVIEW

**Comment by danieldietrich** [comment]
Hi Eric,

this is a good idea! I've played around a bit with it and think that Validation deserves a complete example which devs can copy & paste to be used as base to build upon. Something like this:

I'm not a native english speaker. Feel free to edit / delete / add as much text as you want :-)

--

### VALIDATION CONTROL

Validation is an applicative functor, and facilitates accumulating errors. When trying to compose Monads, the combination process will short circuit at the first encountered error. But 'Validation' will continue processing the combining functions, accumulating all errors. This is especially useful when doing validation of multiple fields, say a web form, and you want to know all errors encountered, instead of one at a time.

**Example:** We retrieve the fields 'name' and 'age' of a web form and want to create either a valid Person or return the list of validation error.

```java
PersonValidator validator = new PersonValidator();

// Valid(Person(Eric, 39))
validator.validatePerson("Eric", 39);

// Invalid(List(Validation contains invalid characters: '!4?', Not born yet.))
validator.validatePerson("Wh4t!?", -1);
```

For that purpose we create a PersonValidator.

```java
class PersonValidator {

    private final String validNameChars = "[a-zA-Z ]";
    private final int minAge = 0;

    public Validation<List<String>, Person> validatePerson(String name, int age) {
        return Validation.combine(validName(name), validAge(age)).ap(Person::new);
    }

    private Validation<String, String> validName(String name) {
        return CharSeq.of(name).replaceAll(validNameChars, "").transform(seq ->
                seq.isEmpty() ? Validation.valid(name)
                              : Validation.invalid("Invalid name characters: '" + seq.distinct().sort() + "'"));
    }

    private Validation<String, Integer> validAge(int age) {
        return (age < minAge) ? Validation.invalid("Too young.")
                              : Validation.valid(age);
    }
}
```

Our Person is represented by a simple value object 

```java
public class Person {

    public final String name;
    public final int age;

    public Person(String name, int age) {
        this.name = name;
        this.age = age;
    }

    @Override
    public String toString() {
        return "Person(" + name + ", " + age + ")";
    }
}
```

**Comment by danieldietrich** [comment]
@enelson I've played around a bit more with Validation. What is the use-case for `Validation.valid(Supplier)` and `Validation.invalid(Supplier)`?

I think we can remove them because Validation needs to be eager initialized in each case because it needs to validate each value on its way down to the whole result.

* `Validation.valid(() -> value)` is the same as `Validation.valid(value)`
* `Validation.valid(supplier)` is the same as `Validation.valid(supplier.get())`
* `Validation.valid(meth::ref)` is the same as `Validation.valid(meth.ref())`

**Comment by enelson** [comment]
@danieldietrich Good idea on the full example. I'll make the changes and submit.

**Comment by enelson** [comment]
@danieldietrich Concerning your other comment about `Validation.valid(Supplier)`, I don't think that it's lazily evaluated. The method immediately calls `supplier.get()` as it's constructing the `Validation`. Here's the method:

``` java
static <E,T> Validation<E,T> valid(Supplier<? extends T> supplier) {
    Objects.requireNonNull(supplier, "supplier is null");
    return new Valid<>(supplier.get());
}
```

I guess I added it so you could construct an instance with complicated construction code inside, like:

// Part of the `ap` method
``` java
invalid( () -> {
    List<E> errors = validation.getError();
    E error = this.getError();
    return errors.append(error);
});
```

But I don't know that I can give any other reasons. It's your call. I personally like them, but you tell me what you think. I appreciate your feedback on all of this.

**Comment by danieldietrich** [comment]
Let's remove it. Suppliers are mostly used in cases where it is not clear if the value is ever needed or the evaluation has to be deferred for some reason.

```java
logger.log(Level.DEBUG, () -> computeMessage());

Try.of(() -> mayThrow());

Lazy.of(() -> evaluatedLater());
```

Using it just for scoping or aligning of code leaves it unclear for the user of an API why the evaluation of the argument may be deferred. That's the main reason why I would remove it. Keeping things as simple as possible.

The example is even shorter when omitting it:

```java
// before
invalid( () -> {
    List<E> errors = validation.getError();
    E error = this.getError();
    return errors.append(error);
});

// after
List<E> errors = validation.getError();
E error = this.getError();
invalid(errors.append(error));
```

Generally I'm a friend of adding features. But this might confuse users. Hope you are d'accord removing it.

**Comment by enelson** [comment]
@danieldietrich Those are some valid points. Sounds good. I'll send you a pull request tomorrow. Thanks Daniel.

**Comment by danieldietrich** [comment]
@enelson Thank you Eric. I'm really thankful for all your help. It is important for me that you have a good feeling with the changes, you invested much time.

**Comment by enelson** [comment]
Ok, new documentation changes have been submitted.

**Comment by danieldietrich** [comment]
Great! I will pull them in - RC3 is near now, it will not hurt, if Validation is not in Maven Central, yet.

Many thanks!

**Pull request merged**
